### ISSUE TITLE
Migrate to spring-boot 2.x

### ISSUE THREAD

**Issue by mbelling** [SolaceProducts/solace-java-spring-boot#13]
Spring Boot is now at 2.0.x as of creation of this ticket, and the Spring Framework is at 5.0.x.  Is there a plan to update the solace-java-spring-boot project to be compatible with these newer frameworks?

**Comment by michalchng** [comment]
Hi mbelling,

Yes there are plans to update the project. I will let you know once there is a date for the updates. 

Regards,

Michael

**Comment by snicoll** [comment]
The current project builds against 1.4 that is EOLed for quite some time. 2.0.x is EOLed as well so please consider building against  `2.1.x` or even trying the `2.2.x` milestones. A good strategy for this project is that have a release lifecycle that somehow matches the Spring Boot generation. Does not have to be an exact match of course as this project can work just fine with 2.0.x, 2.1.x and 2.2x depending on the use of the API.

**Comment by bczoma** [comment]
Sure, we'll have at least 2.1.x in the next release, will check 2.2.x
