### ISSUE TITLE
Simplify environment query in CloudCondition

### ISSUE THREAD

**Issue by snicoll** [SolaceProducts/solace-java-spring-boot#22]
Since Spring Boot 1.3, `VCAP_SERVICES` is handled and added in the environment in a friendly manner, see `CloudFoundryVcapEnvironmentPostProcessor`.

I believe the query in `CloudCondition` can be simplified by checking for `vcap.services.solace-pubsub`. It can then be replaced by a standard `@ConditionalOnProperty`.

**Comment by bczoma** [comment]
Hi Stephane,

Thanks for the suggestion. I looked at checking property and it works fine checking on `vcap.services`, which confirms a CloudFoundry deployment. However, the key for the solace service generated properties is not `vcap.services.<(VCAP_SERVICES)label>.*` but `vcap.services.<(VCAP_SERVICES)name>.*`, where `name` is specific to the deployed service. 
Here is a snippet of our deployed service named `b-test`:
```
VCAP_SERVICES={"solace-pubsub":[{
"label": "solace-pubsub",
"provider": null,
"plan": "enterprise-shared",
"name": "b-test"
...
```
and it generated properties `vcap.services.b-test.*`

The source code seems to confirm that:
https://github.com/spring-projects/spring-boot/blob/v1.3.3.RELEASE/spring-boot/src/main/java/org/springframework/boot/cloud/CloudFoundryVcapEnvironmentPostProcessor.java#L179

I was looking at using a wildcard property name for @ConditionalOnProperty but it didn't seem like possible.

So with the requirement that we'd like to also check on `solace-pubsub` service deployed it seems we'll need to stick to our existing implementation, unless you advise about a workaround.

Thank you!
Balazs

**Comment by snicoll** [comment]
Got it now, I overlooked the "contains". This seems a bit brittle to check for the presence of that string anywhere in the whole `VCAP_SERVICES` document. You could check you run on CloudFoundry with `@ConditionalOnCloudPlatform`. As for parsing the json itself, perhaps something like [java-cfenv](https://github.com/pivotal-cf/java-cfenv) would give you more control?

**Comment by bczoma** [comment]
Thanks Stephane. Ended up making use of @ConditionalOnCloudPlatform. For parsing, I tried using java-cfenv but it requires additional settings like `cf set-env <APP> JBP_CONFIG_SPRING_AUTO_RECONFIGURATION '{enabled: false}'` so instead replaced "contains" with a check of the service presence in the VCAP_SERVICES json.
