### ISSUE TITLE
Wrong spring cloud connectors core coordinates

### ISSUE THREAD

**Issue by snicoll** [SolaceProducts/solace-java-spring-boot#29]
The commit to upgrade to Spring Boot 2 changed [two things](https://github.com/SolaceProducts/solace-java-spring-boot/commit/caa9bcfb3e44b40f75c5402069a4c1aa21d351ee#diff-37807fe6aa3d4f4c73a3dea32014c929R49) with the `spring-cloud-core` artifact:

* A version was explicitly set. Please refrain from doing that as it likely to break dependency management of app using the starter
* The dependency used to be optional and isn't anymore. Is that an oversight?

The name of this artifact was changed as "spring-cloud-core" is very generic. The new name is `spring-cloud-connectors-core` and is managed by Spring Boot 2 so you shouldn't need to specify a version.

**Comment by bczoma** [comment]
Thank you for pointing out, created a PR with the proposed changes
