### ISSUE TITLE
Remove javadoc tags from configuration metadata descriptions

### ISSUE THREAD

**Issue by snicoll** [SolaceProducts/solace-java-spring-boot#36]
Field javadoc of `@ConfigurationProperties`-annotated type should use simple text only (see the [reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-annotation-processor)).

Some keys have `@see` which is rendered as is by tools

![image](https://user-images.githubusercontent.com/490484/65242170-a610de00-dae5-11e9-87c0-c4bf20335b94.png)

**Comment by MichaelDavisSolace** [comment]
Is it acceptable to provide links in plain text like this?
See http://docs.solace.com/Solace-PubSub-Messaging-APIs/Developer-Guide/Configuring-Connection-T.htm

**Comment by snicoll** [comment]
I believe #37 is the follow-up and this issue can therefore be closed?

**Comment by PhilippeKhalife** [comment]
Closing :)
