### ISSUE TITLE
Some updates may be required

### ISSUE THREAD

**Issue by hschaffner** [SolaceProducts/solace-java-spring-boot#4]
The details are good, but a bit stale. 

We are up to 0.1.3 but this maven information references 0.1.1. We support extending all the JCSMP properties (and transport properties) now, but this is not reflected here, in fact the "advanced" do not seem to work with  0.1.1.

Examples of the advanced functionality should be included since there is no further need to extend the current 0.1.3 version to add any JCSMP Session and Transport details. A mention of how to use the advanced auto-configuration properties should be mentioned.

We reference the Spring Docs, but we could use some more discussion on overriding the application.properties file, which is very important for Cloud deployments where configuration features are passed as environment variables (as with OpenShift and Docker). The environment variables changes the delimiter from "." in the application.properties file to "_", which should also be mentioned explicitly.

Heinz

**Comment by bczoma** [comment]
This should be addressed by the latest changes and proposed to be closed.
