### ISSUE TITLE
The API using the autoconfiguration is closing the session. so for each message, we have to open a new connection. If we introduce session.close() the acknowledgement is not handed, it is not thread safe.

### ISSUE THREAD

**Issue by avik86git** [SolaceProducts/solace-java-spring-boot#42]

**Comment by PhilippeKhalife** [comment]
This project has been moved to https://github.com/SolaceProducts/solace-spring-boot , please open a new issue there and provide more details of how or what is closing the session? There is no lifecycle management provided in this project.
